name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0' # Use a supported Xcode version

      - name: Install CocoaPods dependencies
        run: |
          pod install
          pod repo update

      - name: Build app
        run: xcodebuild -workspace ChatAppSwiftUI.xcworkspace -scheme ChatAppSwiftUI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build
